#!/bin/sh

rm -rf build
mkdir build && cd build

cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=21 -DANDROID_PLATFORM="android-21" -DANDROID_ABI="armeabi-v7a with NEON" -DANDROID_STL=c++_static -D CMAKE_BUILD_TYPE=Release -DNEON=ON ..

